sudo: required

language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip
  
services:
  - redis-server
  
branches:
  only:
    - master
    
env:
  global:
  - dbname=test
  - dbhost=localhost
  - dbuser=postgres
  - rdshost=localhost
  
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y autoremove
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-9.5
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo /etc/init.d/postgresql restart
  - psql --version
  
install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  
before_script:
  - psql -U postgres -c 'create database "test";'
  
script:
  - ./go.test.sh
  
after_success:
  - bash <(curl -s https://codecov.io/bash)