sudo: required

language: go

go:
  - 1.7
  - 1.8
  - tip
  
services:
  - redis-server
  
branches:
  only:
    - master
    
env:
  global:
  - dbname=test
  - dbhost=localhost
  - dbuser=postgres
  - rdshost=localhost:6379
  
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y remove --purge postgresql-9.5
  - sudo apt-get -y autoremove
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.6" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-9.6
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.6/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.6/main/pg_hba.conf'
  - sudo /etc/init.d/postgresql restart
  - psql --version
  
install:
  - go get -v github.com/Masterminds/glide 
  - cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
  - glide install 
  - go install ./vendor/github.com/mattn/goveralls 
  
before_script:
  - psql -U postgres -c 'create database "test";'
  
script:
  - go test -race -v
  
after_success:
  - goveralls -service=travis-ci